### ISSUE TITLE
Development stalled?

### ISSUE THREAD

**Issue by postylem** [bperel/wiki-as-git#13]
I see it's not maintained, and it seems broken currently (I think via the nodegit dependency?).

I'd love to hear if development moved to another project, since this tool looks really useful.

Or, is there anyone out there who knows how to get a working version going?

**Comment by bperel** [comment]
Hello, Thank you for your interest in this project that I had almost forgotten the existence of! It is indeed not maintained anymore.

I believe that it should not require too much effort to make it work with a new version of nodegit. Would you be interested in trying to fix it and create a PR?

**Comment by postylem** [comment]
I know nearly nothing of JS/nodeJS, unfortunately, but I'd like to try.  However I am currently even having trouble just installing nodegit from npm, so maybe there are larger issues.

**Comment by bperel** [comment]
Alright. If I have a bit of time this week I will have a look at the issue and keep you posted :-)

**Comment by bperel** [comment]
BTW did you try to use the Docker image as instructed in the README? I just tried it and it seems to work as intended

**Comment by postylem** [comment]
Indeed, the Docker image does work! I was hoping to get a version locally running too, but it isn't super urgent.  I think it might be possible by simply using an earlier version of node, but so far I'm running into issues that are probably simply due to my inexperience with nodejs development.

**Comment by postylem** [comment]
I really appreciate your responding so quickly on this old repo.  I've been playing around with it, and on Docker it seems to work, except for pages with particularly large edit histories.

I opened a new issue (https://github.com/bperel/wiki-as-git/issues/14) here for that, in case it is worth looking at, or if I'm making some silly mistake, not knowing what I'm doing.
